export const CONSTANTS = {
  ROOM_WIDTH: 600,
  ROOM_HEIGHT: 600,
  DOOR_SIZE: 80,
  WALL_THICKNESS: 20,
  PLAYER_SPEED: 200,
  PLAYER_SIZE: 48,
  MINIMAP_SIZE: 150,
  MINIMAP_OFFSET_X: 10,
  MINIMAP_OFFSET_Y: 10,
  MINIMAP_CELL_SIZE: 30
}

export const ROOM_WIDTH = CONSTANTS.ROOM_WIDTH
export const ROOM_HEIGHT = CONSTANTS.ROOM_HEIGHT
export const DOOR_SIZE = CONSTANTS.DOOR_SIZE
export const WALL_THICKNESS = CONSTANTS.WALL_THICKNESS
export const PLAYER_SPEED = CONSTANTS.PLAYER_SPEED
export const PLAYER_SIZE = CONSTANTS.PLAYER_SIZE
export const MINIMAP_SIZE = CONSTANTS.MINIMAP_SIZE
export const MINIMAP_OFFSET_X = CONSTANTS.MINIMAP_OFFSET_X
export const MINIMAP_OFFSET_Y = CONSTANTS.MINIMAP_OFFSET_Y
export const MINIMAP_CELL_SIZE = CONSTANTS.MINIMAP_CELL_SIZE
