export const CONSTANTS = {
  ROOM_WIDTH: 600,
  ROOM_HEIGHT: 600,
  DOOR_SIZE: 80,
  WALL_THICKNESS: 20,
  PLAYER_SPEED: 200,
  PLAYER_SIZE: 48,
  MINIMAP_SIZE: 150,
  MINIMAP_OFFSET_X: 10,
  MINIMAP_OFFSET_Y: 10,
  MINIMAP_CELL_SIZE: 30,
  DOOR_INDICATOR_SIZE: 4
}

